name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Milestone3
    - name: Build
      run: dotnet build --no-restore ./Milestone3
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Milestone3
#     - name: Cache SonarCloud packages
#       uses: actions/cache@v1
#       with:
#         path: ~\sonar\cache
#         key: ${{ runner.os }}-sonar
#         restore-keys: ${{ runner.os }}-sonar
#     - name: Cache SonarCloud scanner
#       id: cache-sonar-scanner
#       uses: actions/cache@v1
#       with:
#         path: .\.sonar\scanner
#         key: ${{ runner.os }}-sonar-scanner
#         restore-keys: ${{ runner.os }}-sonar-scanner
#     - name: Install SonarCloud scanner
#       if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
#       shell: pwsh
#       run: |
#         New-Item -Path .\.sonar\scanner -ItemType Directory
#         dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
#     - name: Build and analyze
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       shell: pwsh
#       run: |
#         .\.sonar\scanner\dotnet-sonarscanner begin /k:"Milestone3" /o:"mtnolasco1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
#         dotnet build ./Milestone3
#         dotnet test ./Milestone3
#         .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    - name: dotnet-sonarcloud
    # You may pin to the exact commit or the version.
    # uses: NazmiAltun/dotnet-sonarscanner-action@435fe12ba60106189d0e52c85869915153b99cf1
      uses: NazmiAltun/dotnet-sonarscanner-action@1.0.6-beta
      with:
        # SonarQube/SonarCloud project key
        project-key: Milestone3
        # SonarQube/SonarCloud project name
        project-name: Milestone3
        # Organization name on SonarQube/SonarCloud
        organization: mtnolasco1
        # Pattern for code coverage exclusion
        # Relative path of sln file
        solution-path: ./Milestone3


